params_mock_cat:
# parameters of the power spectrum as defined in Hustschenreuter et al. 2022
  #P0: 1.1e+14
  #k0: 34
  #gamma: -2.4 
# values used in the tests 
  #P0: 1.5
  #k0: 5.0
  #gamma: -2.5
# values for a Gal RM on large scales
  P0: 3.8
  k0: 5.0
  gamma: -8.0
  maker_params:
    seed: 1000
    maker_type : "seb23" #"seb23"

params:
  nside: 256
  nglobal: 95
  plot_path: "./runs/demo/results_consistent_large_1param_large_scales_disk_off/"
  results_path: "./runs/demo/results_consistent_large_1param_large_scales_disk_off/"

file_params:
  fits_file_path: "data/Faraday/catalog_versions/master_catalog_ver"
  fits_ext: ".fits"

sample_params:
  n: 2
  n_prior: 2
  n_final: 2
  increase_step: 100
  increase_rate: 1.7

controllers:
  sampler:
    n: 500
    n_final: 500
    increase_step: 10
    increase_rate: 1.7
    deltaE: 1.0e-07
    convergence_level: 2
  
  minimizer:
    n: 25
    n_final: 40
    increase_step: "None"
    increase_rate: "None"
    deltaE: 1.0e-07
    convergence_level: 2 #sometimes better 2

  sampler_eg:
    n: 500
    n_final: 500
    increase_step: 10
    increase_rate: 1.7
    deltaE: 1.0e-7
    convergence_level: 2
  
  minimizer_eg:
    n: 40
    n_final: 40
    increase_step: "None"
    increase_rate: "None"
    deltaE: 1.0e-12
    convergence_level: 2 #sometimes better 2

  minimizer_samples:
    n: 25
    n_final: 80
    increase_step: "None"
    increase_rate: "None"
    deltaE: 1.0e-07
    convergence_level: 2