params_mock_cat:


  power_spec:
  # parameters of the power spectrum as defined in Hustschenreuter et al. 2022
    #P0: 1.1e+14
    #k0: 34
    #gamma: -2.4 
  # values used in the tests 
  #  P0: 1.5
  #  k0: 5.0
  #  gamma: -2.5
  # values for a Gal RM on large scales
    P0: 3.8
    k0: 5.0
    gamma: -2.5


  maker_params:
    seed: 1000
    use_mock: True
    disk_on: 1
    maker_type : "seb23" #"consistent"
    eg_on: 1
    n_eg_params: 4
    n_los: 14500 #1030
    noise_eg: 0.06
    noise_gal: 11.5
    npi: 0
    npi_los: 12000

  #Sebastian
  log_amplitude:
    fluctuations:
      asperity: "None"
      flexibility: "1., 1."
      fluctuations: "1.0, 0.5"
      loglogavgslope: "-3.6667, 2."
    offset:
      offset_mean: 4.
      offset_std: "1., 1."
  sign:
    fluctuations:
      asperity: "None"
      flexibility: "1., 1."
      fluctuations: "5.0, 4.0"
      loglogavgslope: "-3.6667, 2."
    offset:
      offset_mean: 0.
      offset_std: "5., 4."

  #tests no disk
  log_amplitude_consistent:
    fluctuations:
      asperity: "None"
      flexibility: "1.e-5,1.e-6"
      fluctuations: "1.0e-5, 1.0e-6"
      loglogavgslope: "-3., 1."
    offset:
      offset_mean: 0.
      offset_std: "1.e-5, 1.e-6"
  sign_consistent:
    fluctuations:
      asperity: "None"
      flexibility: "1., 1."
      fluctuations: "5.0, 4.0"
      loglogavgslope: "-3., 1."
    offset:
      offset_mean: 0.
      offset_std: "5., 4."

params_inference:
  nside: 256
  nglobal: 100
  n_single_fit: 200
  n_samples_posterior: 100
  resume: False
  plot_path: "./runs/demo/results/"
  results_path: "./runs/demo/results/"
  cat_path: "./data/Faraday/catalog_versions/"

file_params:
  fits_file_path: "data/Faraday/catalog_versions/master_catalog_ver"
  fits_ext: ".fits"

sample_params:
  n: 2
  n_prior: 2
  n_final: 20
  increase_step: 8
  increase_rate: 1

controllers:
  sampler:
    n: 500
    n_final: 500
    increase_step:  "None"
    increase_rate:  "None"
    deltaE: 1.0e-07
    convergence_level: 2
  
  minimizer:
    n: 40
    n_final: 40
    increase_step: "None"
    increase_rate: "None"
    deltaE_threshold: 0
    deltaE_start: 1.0e-03
    deltaE_end: 1.0e-07
    convergence_level: 2 #sometimes better 2

  sampler_eg:
    n: 500
    n_final: 500
    increase_step: 10
    increase_rate: 1.7
    deltaE: 1.0e-7
    convergence_level: 2
  
  minimizer_eg:
    n: 40
    n_final: 40
    increase_step: "None"
    increase_rate: "None"
    deltaE: 1.0e-12
    convergence_level: 2 #sometimes better 2

  minimizer_samples:
    n: 25
    n_final: 80
    increase_step: "None"
    increase_rate: "None"
    deltaE: 1.0e-07
    convergence_level: 2

std:
  std_int: 0.5
  std_lum: 0.5
  std_red: 0.5
  std_env: 0.5 
  std_one: 0.5

mean:
  mean_int: 5.0
  mean_lum: 0.0
  mean_red: -0.5
  mean_env: 0.0
  mean_one: 4.0

prior_std:
  prior_std_int: 2.5
  prior_std_lum: 1.0
  prior_std_red: 1.0
  prior_std_env: 1.0 
  prior_std_one: 1.0

prior_mean:
  prior_mean_int: 0.0
  prior_mean_lum: 0.0
  prior_mean_red: 0.0
  prior_mean_env: 0.0
  prior_mean_one: 0.0 