params:
  nside: 256
  nglobal: 20
  plot_path: "./runs/demo/"

file_params:
  fits_file_path: "data/Faraday/catalog_versions/master_catalog_ver"
  fits_ext: ".fits"

controllers:
  sampler:
    n: 500
  minimizer:
    n: 25
  minimizer_samples:
    n: 80
